import { Inter } from 'next/font/google'
import './globals.css'
import { GeistSans } from "geist/font/sans";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'La Candelaria ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
